version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - "${SSL_PORT}:443"
        - "${HTTP_PORT}:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /etc/letsencrypt/ssl/fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - /etc/letsencrypt/ssl/privkey.pem:/etc/nginx/ssl/privkey.pem
    environment:
      - NODE_ENV=development